### ISSUE TITLE
Powercord chain errors - cannot read property 'click' of null

### ISSUE THREAD

**Issue by Succubyss** [lol219/NitroFlex#2]
I saw some (al beit commented out) code related to Powercord in the plugin, so hopefully this can be addressed.

Getting thousands of these little errors:

![image](https://user-images.githubusercontent.com/87207237/130846982-97ef3ef3-8638-4f50-a057-3a1f9e9cdd63.png)

The plugin seems to be working as intended despite this, so I'm not exactly sure why this is happening, but I imagine it's causing some additional strain on the client's resource usage.

**Comment by lol219** [comment]
Our developpers tried to fix that issue , and it makes it worst so we're not recommanding to use NitroFlex on powercord 
Sorry
